component: website 
name: kxz-website
org: flyingstudio
app: kxz-website
stage: dev

inputs:
  src:
    root: ./
    src: ./
    index: index.html
    websitePath: ./
  region: ap-guangzhou
  protocol: https
  hosts:
    - host: kxz.atcumt.com
      autoRefresh: true
      https:
        switch: on
        http2: on
        certInfo:
          certId: 'ipNt8Gr0'